version: "3.7"
services:
  backend:
    build: "./backend"
    container_name: back-potpourri-music-cifras-container
    image: back-potpourri-music-cifras-image
    restart: always
    env_file:
      - ./backend/.env.prod
    ports:
      - "3004:5000"
  frontend:
    build: "./frontend"
    container_name: front-potpourri-music-cifras-container
    image: front-potpourri-music-cifras-image
    restart: always
    env_file:
      - ./frontend/.env.prod
    volumes:
      - ./frontend/nginx/nginx.config:/etc/nginx/conf.d/default.conf    
    ports:
      - "84:80"
    environment:
      - NGINX_HOST=potpourrimusiccifras.com
      - NGINX_PORT=84

